src/data/MALDataDuplicationDefaultRepository.ts
sorry @nacho, the file was not formatted before i save it
I only change the uid.
=> update uid (and file formatted)

package.json, src/index.tsx, src/webapp/reports/Reports.tsx, src/webapp/reports/admin/AdminReport.tsx, src/webapp/reports/nhwa-approval-status/NHWADataApprovalStatusReport.tsx, src/webapp/reports/nhwa-comments/NHWACommentsReport.tsx, src/webapp/reports/wmr-national-policies/WMRNationalPolicies.tsx, yarn.lock
- Add infra to load custom forms with react app
```
REACT_APP_REPORT_VARIANT=wmr-national-policies
```
=> WMR National Policies

src/data/common/Dhis2ConfigRepository.ts, src/data/reports/mal-data-approval/MalDataApprovalDefaultRepository.ts, src/domain/reports/mal-data-approval/repositories/MalDataApprovalRepository.ts, src/scripts/build-mal-metadata.ts, src/webapp/reports/mal-data-approval/data-approval-list/DataApprovalList.tsx
-   **Issue:** Closes https://app.clickup.com/t/860pk1jwp
=> select old periods for mal data approval report

src/data/reports/mal-data-approval/MalDataApprovalDefaultRepository.ts, src/domain/reports/mal-data-approval/entities/MalDataApprovalItem.ts, src/webapp/reports/mal-data-approval/DataApprovalViewModel.ts, src/webapp/reports/mal-data-approval/data-approval-list/DataApprovalList.tsx
-   **Issue:** Closes https://app.clickup.com/t/36433rp
=> join activate and deactivate monitoring mode

src/data/reports/glass-data-submission/GLASSDataSubmissionDefaultRepository.ts
-   **Issue:** Closes https://app.clickup.com/t/860qemqyc
- There was a request for each `(orgUnitId, period)` pair, but it's possible to use a collection for both params (check https://docs.dhis2.org/en/full/develop/dhis-core-version-master/developer-manual.html#webapi_complete_data_set_registrations). We will be getting more data that we need, but it's usually better to do a single API and ignore the data we are not interested in. So no SQL View has been created, the API seems to work fine for the use case.
- About the org units: instead of performing a request by org unit, we now perform a single request with all the IDs involved, with a 300-id chunk to avoid long URLS (DHIS2 typically fails for > 8kb URL -> 414-uri-too-large). 
- I've converted the keys of type …
=> [glass] Improve data submission get operation to minimize API request

src/data/reports/glass-data-submission/GLASSDataSubmissionDefaultRepository.ts
-   **Issue:** Closes https://app.clickup.com/t/860qfdy81
=> feat: add new dataset upload status

src/data/reports/glass-data-submission/GLASSDataSubmissionDefaultRepository.ts, src/domain/reports/glass-data-submission/entities/GLASSDataSubmissionItem.ts
-   **Issue:** Closes https://app.clickup.com/t/860qev9ng
=> feat: return only amr module glass items

package.json
-   **Issue:** Closes https://app.clickup.com/t/860qev9e2
=> fix: different folder name for glass build

src/data/reports/glass-data-submission/GLASSDataSubmissionDefaultRepository.ts
-   **Issue:** Closes https://app.clickup.com/t/860qgydrq
=> Feat: set questionnaire to incomplete on rejection

src/data/reports/glass-data-submission/GLASSDataSubmissionDefaultRepository.ts
-   **Issue:** Closes https://app.clickup.com/t/860qgmj48
=> Fix/send notifications to users in the ou AND the userGroups

src/data/reports/glass-data-submission/GLASSDataSubmissionDefaultRepository.ts
-   **Issue:** Closes https://app.clickup.com/t/860qr7tr0
=> feat: filter out objects user has no access to

src/data/common/Dhis2ConfigRepository.ts, src/domain/common/entities/ReportType.ts, src/webapp/utils/reportType.ts
-   **Issue:** Closes https://app.clickup.com/t/860q2nyqz
=> feat: remove nhwa calls from csy audit filter reports

src/webapp/reports/glass-data-submission/glass-data-submission-list/DataSubmissionList.tsx
-   **Issue:** Closes https://app.clickup.com/t/860qwem6f
=> feat: include submissions from 2016

i18n/en.pot, i18n/es.po, src/webapp/reports/csy-audit-emergency/CSYAuditEmergencyReport.tsx, src/webapp/reports/csy-audit-trauma/CSYAuditTraumaReport.tsx
📌 References Issue: Closes #? 
https://app.clickup.com/t/865cvyjpz 
🔥 Notes to the tester 
Already tested by @MiquelAdell](https://github.com/EyeSeeTea/d2-reports/pull/109)
=> fix: change audit filters title

src/data/reports/glass-data-submission/GLASSDataSubmissionDefaultRepository.ts, src/domain/reports/glass-data-submission/entities/GLASSDataSubmissionItem.ts, src/domain/reports/glass-data-submission/repositories/GLASSDataSubmissionRepository.tsx, src/webapp/reports/glass-data-submission/DataSubmissionViewModel.ts, src/webapp/reports/glass-data-submission/glass-data-submission-list/DataSubmissionList.tsx, src/webapp/reports/glass-data-submission/glass-data-submission-list/Filters.tsx
-   **Issue:** Closes https://app.clickup.com/t/860rjup1n
- Added the dataSubmissionPeriod property from the modules dataStore
- Mapped the property to the table rows
- Display "Quarters" filter based on this property
```
```
=> feat: get dataSubmissionPeriod property from dataStore

.github/pull_request_template.md
=> Update pull_request_template.md to add screen capture recommendation

src/data/reports/glass-data-submission/GLASSDataSubmissionDefaultRepository.ts
-   **Issue:** Closes https://app.clickup.com/t/860rkhh3u
- Filter out the events that are not in the year that is getting approved
```
```
=> fix: egasp approval copies all events

package.json
-   **Issue:** Closes https://app.clickup.com/t/860t18h4j
- We overwrite the version in `manifest.webapp` with `--manifest.version=` using the versions in defined in `package.json`
`REACT_APP_DHIS2_BASE_URL=https://dev.eyeseetea.com/who-dev-238/`
run `yarn build` to test
=> feat: report versioning

src/domain/reports/nhwa-auto-complete-compute/usecases/GetAutoCompleteComputeValuesUseCase.ts
-   **Issue:** Closes https://app.clickup.com/t/860rynbqf
Loading datavalues in chunks to avoid errors for too large url.
Add to the .env file the variant: `REACT_APP_REPORT_VARIANT=nhwa-auto-complete-compute`
=> get datavalues in chunks for autocomplete-compute report

src/data/common/DataValuesD2Repository.ts, src/domain/common/entities/DataValue.ts, src/domain/reports/nhwa-auto-complete-compute/usecases/GetAutoCompleteComputeValuesUseCase.ts, src/webapp/reports/common/nhwa-settings.ts
-   **Issue:** Closes https://app.clickup.com/t/869456mh2
#869456mh2
=> increase range of period if no period is selected

src/data/reports/glass-data-submission/GLASSDataSubmissionDefaultRepository.ts, src/domain/reports/glass-data-submission/entities/GLASSDataSubmissionItem.ts
-   **Issue:** Closes https://app.clickup.com/t/8693yfefj
- #8693yfefj
- Appropriated the correct approval mechanism for each module
- Fixed duplication for event and tracker programs to ensure the same events are in non-apvd and apvd program after approval
https://github.com/EyeSeeTea/d2-reports/assets/37223065/d650a2e9-caf8-4017-8917-ab32b2c81df0
```
```
=> Bug fix/tracker and event program duplication in GLASS submission report

src/data/common/DataValuesD2Repository.ts, src/domain/common/entities/Stats.ts, src/domain/reports/nhwa-auto-complete-compute/usecases/FixAutoCompleteComputeValuesUseCase.ts, src/webapp/components/alert-stats-errors/AlertStatsErrors.tsx, src/webapp/components/alert/Alert.tsx, src/webapp/reports/nhwa-auto-complete-compute/NHWAAutoCompleteCompute.tsx, src/webapp/reports/nhwa-fix-totals-activity-level/NHWAFixTotals.tsx, src/webapp/reports/nhwa-subnational-correct-orgunit/NHWASubnationalCorrectOrgUnit.tsx
-   **Issue:** Closes https://app.clickup.com/t/8694aw1pa
[DHIS2-Reports_error_messages.webm](https://github.com/EyeSeeTea/d2-reports/assets/461124/3c7052fb-1af4-4845-adf5-422eb6efb865)
#8694aw1pa
=> show errors for autocomplete compute report.

src/webapp/reports/Reports.tsx
-   **Issue:** Closes https://app.clickup.com/t/8694b877m
Update `key` in dataStore from `nhwa-auto-complete-compute-subnational` to `nhwa-subn-auto-complete-compute`.
#8694b877m
=> update subnational report key value

src/data/common/Dhis2ConfigRepository.ts, src/data/reports/mal-data-approval/MalDataApprovalDefaultRepository.ts, src/webapp/reports/mal-data-approval/DataApprovalViewModel.ts, src/webapp/reports/mal-data-approval/data-approval-list/DataApprovalList.tsx
-   **Issue:** Closes https://app.clickup.com/t/8694pyaup
```
REACT_APP_REPORT_VARIANT=mal-approval-status
```
#8694pyaup
=> Remove all instances of old wmr form dataset

src/compositionRoot.ts, src/data/reports/glass-data-submission/GLASSDataSubmissionDefaultRepository.ts, src/domain/reports/glass-data-submission/entities/GLASSDataSubmissionItem.ts, src/domain/reports/glass-data-submission/entities/OrgUnit.ts, src/domain/reports/glass-data-submission/repositories/GLASSDataSubmissionRepository.tsx, src/domain/reports/glass-data-submission/usecases/GetOrgUnitsWithChildrenUseCase.ts, src/domain/reports/glass-data-submission/usecases/UpdateGLASSSubmissionUseCase.ts, src/webapp/reports/glass-data-submission/glass-data-submission-list/DataSubmissionList.tsx, src/webapp/reports/glass-data-submission/glass-data-submission-list/Filters.tsx, src/webapp/reports/glass-data-submission/glass-data-submission-list/useDataSubmissionActions.tsx, src/webapp/reports/glass-data-submission/glass-data-submission-list/useDataSubmissionFilters.tsx
-   **Issue:** Closes https://app.clickup.com/t/8694yzhxa
https://github.com/EyeSeeTea/d2-reports/assets/37223065/3c5e291f-ee8c-4831-8edc-d62213233a64
#8694yzhxa
```
```
=> Include current year in GLASS submission report

src/data/reports/glass-data-submission/GLASSDataSubmissionDefaultRepository.ts, src/webapp/reports/glass-data-submission/glass-data-submission-list/DataSubmissionList.tsx, src/webapp/reports/glass-data-submission/glass-data-submission-list/useDataSubmissionList.tsx
-   **Issue:** Closes https://app.clickup.com/t/86959a3ky
https://github.com/user-attachments/assets/c3897859-8a97-4bc8-8ed1-4d2fb6d205cd
```
```
#86959a3ky
=> [GLASS] Get questionnaire datasets from datastore

i18n/en.pot, i18n/es.po, src/compositionRoot.ts, src/data/common/DataSetD2Repository.ts, src/domain/common/entities/DataSet.ts, src/domain/common/repositories/DataSetRepository.ts, src/domain/reports/WmrDiffReport.ts, src/domain/reports/mal-data-approval/usecases/GetMalDataDiffUseCase.ts, src/domain/reports/mal-data-approval/usecases/GetMalDataSetsUseCase.ts, src/webapp/reports/mal-data-approval/DataDifferencesList.tsx
-   **Issue:** Closes https://app.clickup.com/t/8695ud70y
**WMR Form DataSet**
**WMR Form Approval DataSet**
**Differences**
Generate report:
Set variant in .env `REACT_APP_REPORT_VARIANT=mal-approval-status`.
Build report:
```bash
yarn build-report
```
Report will be generated in `/dist/index.html`
#8695ud70y
=> check diff between WMR dataSet and approval dataSet

src/compositionRoot.ts, src/data/common/DataSetD2Repository.ts, src/data/common/Dhis2ConfigRepository.ts, src/data/common/Dhis2OrgUnitsRepository.ts, src/domain/common/entities/OrgUnit.ts, src/domain/common/usecases/GetAllOrgUnitsByLevelUseCase.ts, src/domain/reports/nhwa-fix-totals/GetTotalsByActivityLevelUseCase.ts, src/webapp/reports/Reports.tsx, src/webapp/reports/common/Filters.tsx, src/webapp/reports/nhwa-fix-totals-activity-level/NHWAFixTotals.tsx
-   **Issue:** Closes https://app.clickup.com/t/8696n6reg
[DHIS2-Reports_Activity_level_region.webm](https://github.com/user-attachments/assets/a1129e83-95d4-49d4-949b-8ff2c9de542e)
#8696n6reg
=> allow regions to be selectable in activity level report

package.json, src/data/reports/glass-data-submission/GLASSDataSubmissionDefaultRepository.ts, yarn.lock
-   **Issue:** Closes #8697kr6qt [Upgrade to v2.41 glass-submission report](https://app.clickup.com/t/8697kr6qt)
- upgrade d2-api from 1.9.3 to 1.18.0-beta.1
- Upgrade to v2.41 glass-submission report
[Screencast from 2025-01-31 14-55-41.webm](https://github.com/user-attachments/assets/ec95caa6-15e9-4ded-9e26-e4e722919bda)
[Screencast from 2025-01-31 14-59-16.webm](https://github.com/user-attachments/assets/311d9a74-657a-48a1-a1ba-2f23086242e2)
[Screencast from 2025-01-31 14-56-58.webm](https://github.com/user-attachments/assets/ab1b91c7-c5ce-469c-af17-cf5f80d61a18)
REACT_APP_DHIS2_BASE_URL=https://dev.eyeseetea.com/who-dev-238
Files used to submit them in glass and after approve them in the app:
[AMC-Product Level …
=> Upgrade d2-api from 1.9.3 to 1.18.0-beta.1and glass-submission report new api tracker v2.41
